version: '3.8'

services:

  eureka-server:
    build: ./eureka-server
    ports:
      - "8761:8761"

  ms-usuarios:
    build: ./api-usuarios
    ports:
      - "8081:8081"
    depends_on:
      - eureka-server

  ms-donaciones:
    build: ./donaciones
    ports:
      - "8082:8082"
    depends_on:
      - eureka-server
  ms-inventario:
    build: ./inventario
    ports:
      - "8083:8083"
    depends_on:
      - eureka-server
  ms-logistica:
    build: ./logistica
    ports:
      - "8084:8084"
    depends_on:
      - eureka-server
  ms-necesidades:
    build: ./necesidades
    ports:
      - "8085:8085"
    depends_on:
      - eureka-server
  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server