version: '3.8'
services:
  ms-usuarios:
    image: ${ECR_REGISTRY}/donatonback/ms-usuarios:latest
    container_name: ms-usuarios
    restart: always
    ports:
      - "8081:8081"
    environment:
      - EUREKA_URI=http://${EUREKA_PRIVATE_IP}:8761/eureka/
      - HOST_PRIVATE_IP=${MY_EC2_PRIVATE_IP}
      - SERVER_PORT=8081
      - SPRING_APPLICATION_NAME=ms-usuarios
  ms-donaciones:
    image: ${ECR_REGISTRY}/donatonback/ms-donaciones:latest
    container_name: ms-donaciones
    restart: always
    ports:
      - "8082:8082"
    environment:
      - EUREKA_URI=http://${EUREKA_PRIVATE_IP}:8761/eureka/
      - SERVER_PORT=8082
      - SPRING_APPLICATION_NAME=ms-donaciones