version: '3.8'
services:
  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
  ms-inventario:
    image: ${ECR_REGISTRY}/donatonback/ms-inventario:latest
    container_name: ms-inventario
    restart: always
    ports:
      - "8083:8083"
    environment:
      - EUREKA_URI=http://${EUREKA_PRIVATE_IP}:8761/eureka/
      - SERVER_PORT=8083
      - SPRING_APPLICATION_NAME=ms-inventario
  ms-logistica:
    image: ${ECR_REGISTRY}/donatonback/ms-logistica:latest
    container_name: ms-logistica
    restart: always
    ports:
      - "8084:8084"
    environment:
      - EUREKA_URI=http://${EUREKA_PRIVATE_IP}:8761/eureka/
      - SERVER_PORT=8084
      - SPRING_APPLICATION_NAME=ms-logistica
  ms-necesidades:
    image: ${ECR_REGISTRY}/donatonback/ms-necesidades:latest
    container_name: ms-necesidades
    restart: always
    ports:
      - "8085:8085"
    environment:
      - EUREKA_URI=http://${EUREKA_PRIVATE_IP}:8761/eureka/
      - SERVER_PORT=8085
      - SPRING_APPLICATION_NAME=ms-necesidades
      - REDIS_HOST=redis