version: '3.8'
services:
  eureka:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.us-east-1.amazonaws.com/donaton/eureka:latest
    ports:
      - "8761:8761"
    environment:
      - SERVER_PORT=8761
      - SPRING_APPLICATION_NAME=eureka-server
    restart: always

  api-usuarios:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.us-east-1.amazonaws.com/donaton/api-usuarios:latest
    ports:
      - "8081:8081"
    environment:
      - SERVER_PORT=8081
      - SPRING_APPLICATION_NAME=ms-usuarios
      - EUREKA_URI=http://eureka:8761/eureka/
    depends_on:
      - eureka
    restart: always

  api-donaciones:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.us-east-1.amazonaws.com/donaton/api-donaciones:latest
    ports:
      - "8082:8082"
    environment:
      - SERVER_PORT=8082
      - SPRING_APPLICATION_NAME=ms-donaciones
      - EUREKA_URI=http://eureka:8761/eureka/
    depends_on:
      - eureka
    restart: always

  api-inventario:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.us-east-1.amazonaws.com/donaton/api-inventario:latest
    ports:
      - "8083:8083"
    environment:
      - SERVER_PORT=8083
      - SPRING_APPLICATION_NAME=ms-inventario
      - EUREKA_URI=http://eureka:8761/eureka/
    depends_on:
      - eureka
    restart: always

  api-logistica:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.us-east-1.amazonaws.com/donaton/api-logistica:latest
    ports:
      - "8084:8084"
    environment:
      - SERVER_PORT=8084
      - SPRING_APPLICATION_NAME=ms-logistica
      - EUREKA_URI=http://eureka:8761/eureka/
    depends_on:
      - eureka
    restart: always

  api-necesidades:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.us-east-1.amazonaws.com/donaton/api-necesidades:latest
    ports:
      - "8085:8085"
    environment:
      - SERVER_PORT=8085
      - SPRING_APPLICATION_NAME=ms-necesidades
      - EUREKA_URI=http://eureka:8761/eureka/
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - eureka
      - redis
    restart: always

  gateway:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.us-east-1.amazonaws.com/donaton/gateway:latest
    ports:
      - "8086:8086"
    environment:
      - SERVER_PORT=8086
      - SPRING_APPLICATION_NAME=api-gateway
      - EUREKA_URI=http://eureka:8761/eureka/
      - USUARIOS_URI=lb://ms-usuarios
      - DONACIONES_URI=lb://ms-donaciones
      - NECESIDADES_URI=lb://ms-necesidades
      - INVENTARIO_URI=lb://ms-inventario
      - LOGISTICA_URI=lb://ms-logistica
    depends_on:
      - eureka
    restart: always

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: always
