
# Nombre del microservicio (como se verá en Eureka)
spring.application.name=usuarios-service


spring.mongodb.uri=mongodb+srv://admin_donaton:conexmongo@cluster0.xglvnxz.mongodb.net/usuarios
server.port=8081