apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/donatonback/api-gateway:latest
          ports:
            - containerPort: 8086
          env:
            - name: SERVER_PORT
              value: "8086"
            - name: SPRING_APPLICATION_NAME
              value: "api-gateway"
            - name: EUREKA_URI
              value: "http://eureka-service:8761/eureka/"
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service
spec:
  selector:
    app: api-gateway
  ports:
    - port: 8086
      targetPort: 8086
  type: ClusterIP
