server:
  port: 8761 #puerto por defecto de eureka

spring:
  application:
    name: eureka-server #el nombre del servicio

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
