server:
  port: ${SERVER_PORT:8085}

spring:
  application:
    name: ${SPRING_APPLICATION_NAME:ms-necesidades}
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  cache:
    type: redis
    redis:
      time-to-live: 10m #cache de destruye cada 10 minutos
      cache-null-values: false

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}
