name: Deploy Backend Donaton

on:
  push:
    branches: [ "main", "master" ]
    paths:
      - "api-**/**"
      - "eureka/**"
      - "gateway/**"
      - "docker-compose.yml"
  workflow_dispatch:

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest
    strategy:
      # Lista de carpetas que coinciden con tus nombres de ECR
      matrix:
        service: [api-donaciones, api-gateway, api-inventario, api-logistica, api-necesidades, api-usuarios, eureka]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and Push
        run: |
          IMAGE_URI="${{ secrets.ECR_REGISTRY }}/${{ matrix.service }}:latest"
          echo "Construyendo ${{ matrix.service }}..."
          cd ${{ matrix.service }}
          docker build -t $IMAGE_URI .
          docker push $IMAGE_URI

  trigger-ssm-deploy:
    needs: build-push-deploy
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Execute Remote Deploy via SSM
        run: |
          aws ssm send-command \
            --instance-ids ${{ secrets.EC2_INSTANCE_ID }} \
            --document-name "AWS-RunShellScript" \
            --comment "Actualizando backend en EC2 Privada" \
            --parameters '{"commands":[
              "set -e",
              "cd /home/ec2-user",
              "aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.ECR_REGISTRY }}",
              "docker-compose pull",
              "docker-compose up -d",
              "docker image prune -f"
            ]}'
